baseURL: 'https://exilland.dev/'
title: Exilland
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

googleAnalytics: UA-178149880-4

DefaultContentLanguage: en

languages:
  en:
    weight: 2
    LanguageName: English
  ru:
    wight: 1
    LanguageName: Русский
    menu:
      main:
        - identifier: staff-only
          name: Staff Only
          url: /staff-only/
          weight: -100
        - identifier: contact
          name: Контакты
          url: /contact/

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Exilland
  description: "Exilland Indie Game Development Studio"

  images: ExillandFullLogo.png

  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
    favicon: /favicon/favicon.ico

  label:
    text: "Exilland"
    icon: /ExillandSmallLogo.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Exilland
    imageUrl: /ExillandFullLogo.png
    imageTitle: Exilland
    buttons:
      - name: Staff Only
        img: /StaffOnlySmallLogo.png
        url: staff-only
      

  # home-info mode

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/exilland'
    - name: vk
      url: 'https://vk.com/staffonly_exilland'
    - name: gamejolt
      url: 'https://gamejolt.com/games/staffonly/541130'
    - name: itchio
      url: 'https://exilland.itch.io/staff-only'
    - name: steam
      url: 'https://store.steampowered.com/app/1440350/Staff_Only/'



menu:
  main:
    - identifier: staff-only
      name: Staff Only
      url: /staff-only/
      weight: -100
    - identifier: contact
      name: Contacts
      url: /contact/